<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;

class AdminDatasetController extends Controller
{
    public function index()
    {
        return view('admin.datasets');
    }

    public function generate()
    {
        Artisan::call('ml:generate-user-churn-dataset');
        Log::info('Dataset generated by admin panel at ' . now());
        return response()->json(['success' => true]);
    }

    public function download()
    {
        $path = storage_path('app/ml_datasets/user_churn_training_dataset.csv');
        if (!file_exists($path)) {
            abort(404);
        }
        return response()->download($path);
    }

    public function logs()
    {
        $logPath = storage_path('logs/laravel.log');
        $logs = file_exists($logPath) ? file_get_contents($logPath) : '';
        return response()->json(['logs' => $logs]);
    }
}
