<?php

namespace App\Http\Controllers;

use App\Models\DatasetBuildLog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;

class DatasetBuilderController extends Controller
{
    public function index()
    {
        $logs = DatasetBuildLog::orderBy('created_at', 'desc')->paginate(10);
        return view('dataset.index', compact('logs'));
    }

    public function trigger()
    {
        Artisan::call('ml:generate-user-churn-dataset');
        Log::info('Dataset generated by admin panel at ' . now());
        return redirect()->route('dataset.index')->with('success', 'Dataset generation triggered!');
    }

    public function download($id)
    {
        $log = DatasetBuildLog::findOrFail($id);
        return response()->download(storage_path("app/ml_datasets/{$log->file_path}"));
    }
}
